pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git url: 'https://github.com/giosassis/serveless-api', branch: 'main' 
                sh "npm i"  
            }
        }

        stage('Run unit test') {
            steps {
                sh "echo TODO"  
            }
        }

        stage('Deploy') {
            steps {
                sh "echo TODO"
            }
        }
    }
}